version: '3'

services:
  es:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    env_file:
      - .envs/development.env
    volumes:
      - .:/code:delegated
    ports:
      - "8000:8000"
    depends_on:
      - es
