version: '3'

services:
  es:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  postgres:
    image: "postgres"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    env_file:
      - .envs/development.env
    volumes:
      - .:/code:delegated
    ports:
      - "8000:8000"
    depends_on:
      - es
